DESCRIPTION_MIN_CHARS = 40
DESCRIPTION_MAX_CHARS = 1200
LONG_SKILL_LINES = 400
LONG_SKILL_TOKEN_ESTIMATE = 7000
SIMILARITY_THRESHOLD = 0.42

RUN_STATUS_PROPOSED = "proposed"
BACKUP_POLICIES = ("off", "targeted", "full")
ACTIVE_STATES = ("active", "inactive", "unknown")

ACTION_KEEP = "保留"
ACTION_ADJUST_DESCRIPTION = "调整描述"
ACTION_SPLIT_CONTENT = "拆分内容"
ACTION_MERGE_OR_DEDUPE = "合并或去重"
ACTION_ARCHIVE_CANDIDATE = "归档候选"
ACTION_SECURITY_REVIEW = "人工安全检查"
ACTION_NOTE_ONLY = "只提示不修改"
